### ISSUE TITLE
conf/reference_pts.json is missing

### ISSUE THREAD

**Issue by MaximilianKleissl** [masouduut94/volleyball_analytics#3]
Hi @masouduut94,

I like your approach to volleyball analytics and tried running the code on my system.
Unfortunately, I cannot run it because `conf/reference_pts.json` seems missing in the repo, and I cannot figure out how to replace it.

Thanks,
Max

**Comment by masouduut94** [comment]
Hi Maximilian

First I appreciate your gratitude and feedback as well.

The json file you mentioned has contents related to court and net
coordinations.

I use gui script to prepare it. You have to use the gui. Maybe it throws
error, but in the future I fix everything.

Im going to create a more thorough tutorial to make sure everybody knows
how to prepare the requirements for running the scripts.

Please make sure you read the whole wiki and readme file.

Bests,
Masoud

**Comment by MaximilianKleissl** [comment]
Thanks for the quick answer. Got it running now!
